# Generated by Django 3.1.3 on 2020-11-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='uploadingdate',
            new_name='uploadDate',
        ),
    ]
